export const SET_DATA_LOADED = 'SET_DATA_LOADED';

export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';

export const TOGGLE_DETAIL_MODAL = 'TOGGLE_DETAIL_MODAL';
export const RELOAD_DETAIL_MODAL = 'RELOAD_DETAIL_MODAL';

export const REQUEST_CHARACTER_PENDING = 'REQUEST_CHARACTER_PENDING';
export const REQUEST_CHARACTER_SUCCESS = 'REQUEST_CHARACTER_SUCCESS';
export const REQUEST_CHARACTER_FAILED = 'REQUEST_CHARACTER_FAILED';

export const REQUEST_PLANETS_PENDING = 'REQUEST_PLANETS_PENDING';
export const REQUEST_PLANETS_SUCCESS = 'REQUEST_PLANETS_SUCCESS';
export const REQUEST_PLANETS_FAILED = 'REQUEST_PLANETS_FAILED';

export const REQUEST_SPECIES_PENDING = 'REQUEST_SPECIES_PENDING';
export const REQUEST_SPECIES_SUCCESS = 'REQUEST_SPECIES_SUCCESS';
export const REQUEST_SPECIES_FAILED = 'REQUEST_SPECIES_FAILED';

export const REQUEST_FILMS_PENDING = 'REQUEST_FILMS_PENDING';
export const REQUEST_FILMS_SUCCESS = 'REQUEST_FILMS_SUCCESS';
export const REQUEST_FILMS_FAILED = 'REQUEST_FILMS_FAILED';

export const REQUEST_STARSHIPS_PENDING = 'REQUEST_STARSHIPS_PENDING';
export const REQUEST_STARSHIPS_SUCCESS = 'REQUEST_STARSHIPS_SUCCESS';
export const REQUEST_STARSHIPS_FAILED = 'REQUEST_STARSHIPS_FAILED';

export const REQUEST_VEHICLES_PENDING = 'REQUEST_VEHICLES_PENDING';
export const REQUEST_VEHICLES_SUCCESS = 'REQUEST_VEHICLES_SUCCESS';
export const REQUEST_VEHICLES_FAILED = 'REQUEST_VEHICLES_FAILED';

export const DATA_CLASS_CHARACTERS = 'DATA_CLASS_CHARACTERS';
export const DATA_CLASS_PLANETS = 'DATA_CLASS_PLANETS';
export const DATA_CLASS_SPECIES = 'DATA_CLASS_SPECIES';
export const DATA_CLASS_FILMS = 'DATA_CLASS_FILMS';
export const DATA_CLASS_STARSHIPS = 'DATA_CLASS_STARSHIPS';
export const DATA_CLASS_VEHICLES = 'DATA_CLASS_VEHICLES';